### ISSUE TITLE
Horoscope Barchart: suggestion to add Count and (% percentage) value# inside each bar

### ISSUE THREAD

**Issue by sfd99** [rolkra/explore#11]
Horoscope Barchart 
in **{explore} PKG**:
Fun example!. 😀 

But it actually shows 
the expanding power of the {explore} PKG.

In very few lines of R code,
you: 
 **-** generated sample variables
and 
 **-** created a very information-rich plot 
   w/ multiple barcodes...

**Suggestion:** 

Allow User 
to add _actual values_ of
**Count / Frequency ** and **(% Percentage)**,
i.e.:  182 (15%),
_inside_ EACH red & blue bar ?.
(via an _optional_ T/F parameter/argument= in call to explore).

Many applications for this...

**+ Happy 2023 to you too, Roland!.**

**Comment by rolkra** [comment]
I see your point. 
{explore} is designed to have a very simple syntax, so that coding can be done without reading help. Data visualisation that goes in direction of visual design should be done with other packages or directly in ggplot()

However, in case of the horoscope data, there is a simple way to show percentages in the bars. Just use explore_targetpct(), that will show barcharts as %target.

Example:
# use explore
library(explore)

# create data
set.seed(13)   # change as you like!
data <- create_data_empty(obs = 300)
data <- data |> 
  add_var_random_cat("type", c("Work", "Love", "Health")) |> 
  add_var_random_01("success", prob = c(0.3, 0.7)) |> 
  add_var_random_starsign("starsign")

# as percent of target (with labels)
data |> explore_targetpct(type, target = success)
data |> explore_targetpct(starsign, target = success)

# interactive
library(plotly)
data |> explore_targetpct(starsign, target = success) |> ggplotly()
